### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by WraySmith** [ubco-mds-2020-labs/dashboard-project-group14#1]
- [x] add license (MIT)
- [x] proposal (motivation and purpose, description, research questions)
- [x] description of app & sketch (use noun project)
- [x] team work contract and collab doc
- [x] code of conduct
- [x] contributing guidelines
- [ ] make release

**Comment by WraySmith** [comment]
**Nate:**
- description 
**Mitch:**
- getting the new data and transforming into our new dataset
**Ryan:**
- research questions
**Sophia:** 
- motivation and purpose (why, target, role, problem)

description of app and sketch - Thursday after lab

**Comment by WraySmith** [comment]
release will be made after #13 is merged
