### ISSUE TITLE
Dash Layout Updates for Milestone 4

### ISSUE THREAD

**Issue by WraySmith** [ubco-mds-2020-labs/dashboard-project-group14#34]
Based on review of #32, the following won't be implemented in Milestone 2 but should be for Milestone 4:
- [x] speed of Figures 1 and 2 loading is slow
- ~potential change of Figure 2 to an overlaid fill chart (may be dealt with directly in PR #32)~
- [x] general layout (spacing/aesthetics) needs some work
- [x] needs thought into user instructions

**Comment by WraySmith** [comment]
added items that weren't completed as part of Milestone 2 cleanup #38 
- tab 1 lower bar charts: add a slider allowing a user to set a minimum number of user ratings for a game to have to filter on and also a slider for minimum number of games
- tab 2: add a slider to allow a user to set minimum number of user ratings as well as a year-range slider (or a drop-down for start and end year if the slider doesn't fit well)
- try replacing the bar charts with two vertical series of boxplots (each controlled by a time range slider as the bar charts are now, and probably top 10-20 by average or median, whatever looks better) where the user can select either publisher/category/mechanic (same as the top two figures), set a minimum no. of user ratings and minimum number of board games

**Comment by WraySmith** [comment]
From group/Firas feedback from #55:

- [ ] Make tabs more obvious
- [ ] Ensure user instruction can be easily found / have an explanation for user rating
- [ ] Limit whitespace / aesthetics
- [ ] Fix up data table
- [ ] Add headings
- [ ] Consider modification to tab 1 figure 1 or at least ensure colors are different - one thought is to potentially add a toggle for turning on/off points and have all selections shows a mean line (potentially with quantiles shaded) - on the fly mean lines/quantiles in Altair would either need to be preprocessed or use the experimental Altair transformer

**Comment by WraySmith** [comment]
See working ppt for additional tweaks to aesthetics discussions (more than just listed above).

**Comment by WraySmith** [comment]
Closing for Milestone 4, moved one item that was not completed to Issues #69.
