### ISSUE TITLE
Dashboard Updates to be completed for Milestone 2

### ISSUE THREAD

**Issue by WraySmith** [ubco-mds-2020-labs/dashboard-project-group14#38]
Dashboard items to be fixed-up Monday for Milestone 2:

- [ ] fix error that occurs in tab 1 top 2 figures when switching radio buttons
- [ ] update bar charts so time slider goes above charts and so the output for each series of charts is a single faceted image
- [ ] make the default on tab 2 have something that shows a graph
- [ ] switch the order of the board game names in the tab 2 bar chart
- [ ] remove game family from the table and cut down the words in the game table headers
- [ ] update the Graph title to be capitalized on tab 2

**Comment by WraySmith** [comment]
Other items that would be good to do as time permits:

- [ ] add some good looking screenshots to the README (probably using the screen capture functionality from the Altair figures)
- [ ] spend time on the performance of the top 2 figures on the first tab

**Comment by sophiabulcock** [comment]
Since I'm familiar with the layout I will start with:
1. put a subnote/subtitle below the title on the top figure on tab 1 that says "Annual average rating for all board games shown by grey line".
2. make the default on tab 2 have something that shows a graph
3. switch the order of the board game names in the tab 2 bar chart
4. update the Graph title to be capitalized on tab 2
5.  remove game family from the table and cut down the words in the game table headers

**Comment by WraySmith** [comment]
@mqharris to update READMEs in the `data` folder and the `src/scripts` (and rename scripts as required to make the most sense).  Also fix any of the scripts based on the new location of the data folders

**Comment by WraySmith** [comment]
Moved items that won't be completed as part of Milestone 2 to #34
